local_backend: true
backend:
  name: git-gateway
  branch: main
  squash_merges: true
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
publish_mode: simple

collections:
  - name: "miniatures"
    label: "Miniatures"
    folder: "src/content/miniatures"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{creatureType}} - {{designer}}"
    view_filters:
      - label: "Featured"
        field: featured
        pattern: true
      - label: "For Sale"
        field: forSale
        pattern: true
    view_groups:
      - label: "Creature Type"
        field: creatureType
    fields:
      # Basic Info
      - label: "Name"
        name: "title"
        widget: "string"
        required: false
      
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
        
      - label: "Scale"
        name: "scale"
        widget: "select"
        required: false
        options: ["32mm", "54mm", "Other"]
      
      - label: "Creature Type"
        name: "creatureType"
        widget: "select"
        required: false
        options: 
          - "Hero"
          - "Undead"
          - "Goblinoid"
          - "Monstrosity"
          - "Beast"
          - "Dragon"
          - "Demon"
          - "Cultist"
          - "Construct"
          - "Elemental"
          - "Giant"
          - "Humanoid"
          - "Aberration"
          - "Other"
      
      # Photos
      - label: "Photos"
        name: "photos"
        widget: "list"
        required: false
        summary: "Photo {{index}}: {{fields.caption}}"
        view_filters:
          - label: "Has Caption"
            field: caption
            pattern: ".+"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
            hint: "Optional description for this photo"
      
      # Creator Info
      - label: "Designer"
        name: "designer"
        widget: "select"
        required: false
        options: 
          - "Yasashii Kyojin Studio"
          - "Brite Minis"
          - "Artisan Guild"
          - "Clay Cyanide"
          - "Dragon Trappers Lodge"
          - "Flesh of Gods"
          - "Highland Miniatures"
          - "Loot Studios"
          - "Medbury Miniatures"
          - "Mini Monster Mayhem"
          - "Norkers"
          - "Punga Miniatures"
          - "Rocket Pig Games"
          - "Wargames Atlantic"
          - "Other"
      
      # Simplified Pricing Structure
      - label: "Pricing"
        name: "pricing"
        widget: "object"
        required: false
        fields:
          - label: "OSR Priming Options"
            name: "osrPriming"
            widget: "object"
            required: false
            fields:
              - label: "Tabletop Scale"
                name: "tabletop"
                widget: "number"
                required: false
                step: 0.01
              - label: "Display Scale (54mm)"
                name: "display"
                widget: "number"
                required: false
                step: 0.01
          
          - label: "Unprimed Options"
            name: "unprimed"
            widget: "object"
            required: false
            fields:
              - label: "Tabletop Scale"
                name: "tabletop"
                widget: "number"
                required: false
                step: 0.01
              - label: "Display Scale (54mm)"
                name: "display"
                widget: "number"
                required: false
                step: 0.01
      
      # Flags
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
        
      - label: "For Sale"
        name: "forSale"
        widget: "boolean"
        default: false

  # Pages Configuration (unchanged)
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/content/pages/homepage.json"
        fields:
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"
            default: "Grim Baddies for Old School Gaming"
          - label: "Hero Subtitle"
            name: "heroSubtitle"
            widget: "text"
            default: "Bold black & white miniatures inspired by OSR artwork. Functional Gaming Minis."
          - label: "Hero Image"
            name: "heroImage"
            widget: "image"
            required: false
          - label: "Hero Image Caption"
            name: "heroImageCaption"
            widget: "string"
            required: false
          - label: "OSR Section Title"
            name: "osrTitle"
            widget: "string"
            default: "The OSR Aesthetic"
          - label: "OSR Section Subtitle"
            name: "osrSubtitle"
            widget: "string"
            default: "Bold & Simple, Just Like OSR Art"
          - label: "OSR Description"
            name: "osrDescription"
            widget: "markdown"
          - label: "Featured Section Title"
            name: "featuredTitle"
            widget: "string"
            default: "Recent Terrors"
          - label: "Featured Section Subtitle"
            name: "featuredSubtitle"
            widget: "string"
            default: "Fresh from the painting table, ready to haunt your campaigns"
          - label: "CTA Title"
            name: "ctaTitle"
            widget: "string"
            default: "Ready to Terrify Your Players?"
          - label: "CTA Description"
            name: "ctaDescription"
            widget: "text"
          - label: "Primary Button Text"
            name: "primaryButtonText"
            widget: "string"
            default: "Commission Your Monsters"
          - label: "Secondary Button Text"
            name: "secondaryButtonText"
            widget: "string"
            default: "Follow the Process"